# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.0.3
group=net.ent.entate
java_version=21

# Common
minecraft_version=1.21.1
mod_name=EntArmorTrimExpanded
mod_author=TheFlyingEnt aka Ent
mod_id=entate
license=BSD-3-Clause
credits=Wattle's Community
description=         Adds support Animated Trim Material. \n    And yes Fikus-my7ed, This took 2 weeks cause I have a life...
minecraft_version_range=[1.21.1, 1.21.2)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21
parchment_version=2024.11.10

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.116.5+1.21.1
fabric_loader_version=0.16.14

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=21.1.209
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
